name: chatting_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.1 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  firebase_core: ^2.13.1
  firebase_analytics: ^10.4.2
  http: ^0.13.5
  firebase_auth: ^4.6.2
  flutter_svg: ^2.0.6
  equatable: ^2.0.5
  intl: ^0.17.0
  flutter_facebook_auth: ^5.0.11
  cloud_firestore: ^4.8.0
  get: 4.6.5
  flutter: 
    sdk: flutter
  firebase_storage: ^11.2.2
  sticky_grouped_list: ^3.1.0
  bubble: ^1.2.1
  collection: ^1.17.1
  emoji_picker_flutter: ^1.6.0

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/icons/
    - assets/images/
  uses-material-design: true

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
