// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwX6g2gwRJbS-jL0xN-65qM526ml7rNco',
    appId: '1:11072957061:web:047d34b6eaefccabe9d7ec',
    messagingSenderId: '11072957061',
    projectId: 'chatting-app-a440e',
    authDomain: 'chatting-app-a440e.firebaseapp.com',
    storageBucket: 'chatting-app-a440e.appspot.com',
    measurementId: 'G-VQP2VFR83S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgCcob3pgiUvB3TP0fUB5DXg4xOay22Qc',
    appId: '1:11072957061:android:ee5c62c3e3831895e9d7ec',
    messagingSenderId: '11072957061',
    projectId: 'chatting-app-a440e',
    storageBucket: 'chatting-app-a440e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyrBDLlb8RRK-eY9BZl-iCT44jj6FTK8A',
    appId: '1:11072957061:ios:3c21710b3506a924e9d7ec',
    messagingSenderId: '11072957061',
    projectId: 'chatting-app-a440e',
    storageBucket: 'chatting-app-a440e.appspot.com',
    iosClientId: '11072957061-2s4qb3n0702hd6b42lks74e87c18e916.apps.googleusercontent.com',
    iosBundleId: 'com.example.chattingApp',
  );
}
